name: dclasso
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # project-specific packages
  - optax
  - pytorch
  # required
  - codecov
  - dvc
  - dvc-gdrive
  - ipython
  - jupyterlab
  - libblas=*=*_mkl
  - nextflow
  - pip
  - pytest
  - python=3.10
  - r-irkernel
  # usually good to have
  - jax
  - r
  - rpy2
  - r-tidyverse
  - pandas
  - scikit-learn
  - plotly
  - pip:
    - jax[cpu]
    - kaleido
  # - seaborn
